app/src/lib/components/Gallery/Gallery.tsx, app/src/lib/components/Gallery/Item.tsx
1. create Gallery component
2. create Item component used in Gallery component
these aren't tested yet
it'll be later
=> Feat create Gallery component #7

app/.eslintrc.js, app/src/App.tsx, app/src/lib/components/TechStack/TechStacks/ProgressBar.tsx, app/src/lib/components/TechStack/TechStacks/TechStack.tsx, app/src/lib/components/TechStack/TechStacks/TechStackList.tsx, app/src/lib/components/TechStack/TechStacks/TechStackName.tsx, app/src/lib/components/TechStack/TechStacks/TechStacks.tsx, app/src/lib/index.ts
I suggest that make new global type and object named COLORS.
If we make global COLORS object and types we can easily select colors to every component this is quite sexy and cool I think.
So what I want to suggest exactly is not  make options (like "poppy" and "blossom") but create COLORS object!
=> Refactor TechStack components

app/src/lib/components/Experience/Experience.tsx, app/src/lib/components/Experience/History/Basic.tsx, app/src/lib/components/Experience/History/index.tsx
=> [Feat]: modify Experience Component architecture to receive theme props #36

app/src/lib/components/Experience/Experience.tsx, app/src/lib/components/Experience/History/Basic.tsx, app/src/lib/components/Experience/History/Box.tsx, app/src/lib/components/Experience/History/index.tsx
=> [Feat] create box component to theme Experience (#36)

app/src/App.tsx, app/src/lib/components/Experience/Experience.tsx, app/src/lib/components/Experience/History/Vertical.tsx, app/src/lib/components/Experience/History/index.tsx
- Shape : round-square
- Title Color : red
ex)
=> [Feat] create vertical component that one of theme of experience (#36)

app/src/lib/common/hooks/useInteractiveMouseMove.tsx
this hook is for DOM that need to interactiveMouseMove
=> [Feat]: create useInteractiveMouseMove custom hook #36

app/src/lib/components/Channels/Channels.tsx, app/src/lib/components/Contact/Contact.tsx, app/src/lib/components/Header/Header.tsx, app/src/lib/components/Header/Logo.tsx
=> [Refactor] Change wrong names 'uri' to 'url' #45

app/src/App.tsx, app/src/lib/components/Header/Header.tsx, app/src/lib/components/Header/Logo.tsx, app/src/lib/components/Header/SideContainer/SideBar.tsx, app/src/lib/components/Header/SideContainer/SideBarIcon.tsx, app/src/lib/components/Header/SideContainer/SideContainer.tsx
closed #66 
* styles 프롭스를 전부 제거 -> 각각 프롭스를 주입하는 방식으로 변경하였음.
=> [Refactor] remove props called 'styles' and must append those props in origin props #66

app/src/App.tsx, app/src/lib/common/types/contact.ts, app/src/lib/components/Carousel/Carousel.tsx, app/src/lib/components/Channels/Channels.tsx, app/src/lib/components/Contact/Contact.tsx, app/src/lib/components/Experience/Experience.tsx, app/src/lib/components/Gallery/Gallery.tsx, app/src/lib/components/Header/Header.tsx, app/src/lib/components/Header/SideContainer/SideContainer.tsx, app/src/lib/components/Intro/Intro.tsx, app/src/lib/components/Masonry/Masonry.tsx, app/src/lib/components/TechStack/TechStacks/TechStackList.tsx
#64 
* 각 Props에 등록된 ID를 수집하여 사이드바에 등록하는 기능 구현
=> Implementation of the function of collecting id registered in each prop and registering it in the sidebar #64

app/package.json
[Build] update version to v0.3.4
=> [Build] update version to v0.3.4

app/package.json, app/src/App.tsx, app/src/lib/components/Contact/Contact.tsx, app/src/lib/components/Header/SideContainer/SideContainer.tsx
=> [feature/pwr/#80]

app/src/lib/components/Carousel/Carousel.tsx, app/src/lib/components/Carousel/hooks.tsx
1. 오토플레이 컨트롤 버튼 정상 동작되도록 수정
2. 무한 캐러셀 동작 수정
=> [Fix] fix carousel autoplay bug (#48)

app/src/lib/common/types/ComponentTypes/Header/HeaderLogoType.ts, app/src/lib/common/types/ComponentTypes/Header/HeaderType.ts, app/src/lib/common/types/ComponentTypes/Header/SideBar/SideBarIconType.ts, app/src/lib/common/types/ComponentTypes/Header/SideBar/SideBarType.ts, app/src/lib/components/Channels/Channels.tsx, app/src/lib/components/Header/Header.tsx, app/src/lib/components/Header/HeaderLogo.tsx, app/src/lib/components/Header/SideContainer.tsx, app/src/lib/components/Header/SideContainer/SideBarIcon.tsx
=> [feature/pwr/#92]

app/src/lib/common/types/ComponentTypes/GalleryType.ts, app/src/lib/components/Gallery/Gallery.tsx
1. 반응형 분기 추가
- 1280px (태블릿) 
- 568px (모바일)
2. props 이름 변경 (col -> column)
---
**반응형 변경 사항**
5
=> [Feat] reinforce Gallery Component (#81)

app/package.json, app/src/lib/common/types/ComponentTypes/TechStack/ProgressBarType.ts, app/src/lib/components/TechStack/TechStacks/ProgressBar.tsx, app/src/lib/components/TechStack/TechStacks/TechStackList.tsx
#102 
* rate 표시 여부 : ```isHiddenRateText: boolean``` isHiddenRateText 프롭스 추가
* border 안보이게 : ```border: string``` border 프롭스 추가
=> [Feat] add props in ProgressBar components

app/src/App.tsx, app/src/lib/common/types/ComponentTypes/VisitorCommentType.ts, app/src/lib/components/VisitorComment/CommentInput.tsx, app/src/lib/components/VisitorComment/CommentList/Basic.tsx, app/src/lib/components/VisitorComment/CommentList/Box.tsx, app/src/lib/components/VisitorComment/CommentList/Vertical.tsx, app/src/lib/components/VisitorComment/CommentList/index.tsx, app/src/lib/components/VisitorComment/ScrollProgress.tsx, app/src/lib/components/VisitorComment/VisitorComment.tsx, app/src/lib/index.ts
rate 표시 여부 props는 해당 pr 머지후 적용 시키겠습니다
=> [Feat] create the VisitorComment components (#90)

README.md, package.json
[Docs] Update MarkUp of README.md
=> [Docs] Update MarkUp of README.md

README.md, package-lock.json, package.json
[Docs] write document for sidebar
=> [Docs] write document for sidebar

README.md, src/lib/common/types/ComponentTypes/Contact/ContactType.ts, src/lib/common/types/ComponentTypes/ExperienceType.ts, src/lib/common/types/ComponentTypes/IntroType.ts, src/lib/components/Contact/Contact.tsx, src/lib/components/Contact/ContactForm.tsx, src/lib/components/Experience/Experience.tsx, src/lib/components/Intro/Intro.tsx
1. 옵셔널 props 제거후 개별 props로 전환
2. typedoc 수정
3. README 수정
배열로 되어있는 props는 옵셔널이 아니라고 판단 (오로지 객체로 되어있는 props만이 옵셔널이라고 판단하였음)
=> [Refactor] remove optional props

src/App.tsx, src/lib/common/types/ComponentTypes/ChannelType.ts, src/lib/common/types/ComponentTypes/Header/SideBar/SideBarType.ts, src/lib/common/types/ComponentTypes/Header/SideContainerType.ts, src/lib/common/types/ComponentTypes/SkillType.ts, src/lib/components/Channels/Channel.tsx, src/lib/components/Channels/Channels.tsx, src/lib/components/Header/Header.tsx, src/lib/components/Header/SideContainer.tsx, src/lib/components/Skill/Skill.tsx, src/lib/index.ts
#153 
> add components such as 'Skill' and 'Channel' etc.
> refer: changed default value of props such as title, iconName, iconSize. and added props the iconColor!!
```ts
/**
* Express your skills using the Skill component.
*
* @props title: Main text that expresses the skill (default: 'javascript')
* @props titleSize: Title size style (default: '24px')
* @props isHiddenTitle: If this value is set to True, you can hide the title. (default: false)
* @props iconName: Enter the name of the icon you searched on the following site. (default: 'ion:logo-javascript') {@link https://icon-sets.iconify.design/}
* @props iconSize: Icon size style (defualt: '40px')
* @props iconColor: Icon color style (default: '#F0DB4F')
* @props margin: Skill margin style (defualt: '0px')
* @props padding: Skill …
```
=> [Feat] add components such as 'Skill' and 'Channel' etc. (#153)

.github/workflows/ci.yml, .github/workflows/release-to-npm.yml, .husky/commit-msg, .husky/pre-commit, .husky/prepare-commit-msg, .releaserc, README.md, commitlint.config.js, package-lock.json, package.json
=> [Build] add CICD files and features

.github/workflows/ci.yml, .github/workflows/release-to-npm.yml
[fix(ci.yml): remove lint attr of needs in lint](https://github.com/modern-agile-team/dev-portfolio/commit/bbb1e4b76c47f2050a650305aa07eaa0393aba57)
=> fix(ci.yml): remove lint attr of needs in lint

src/App.css, src/lib/common/types/ComponentTypes/ChannelType.ts, src/lib/common/types/ComponentTypes/Contact/AboutMeInfoType.ts, src/lib/common/types/ComponentTypes/Contact/ContactType.ts, src/lib/common/types/ComponentTypes/Header/HeaderType.ts, src/lib/common/types/ComponentTypes/ImageType.ts, src/lib/common/types/ComponentTypes/IntroType.ts, src/lib/common/types/ComponentTypes/ItemType.ts, src/lib/common/types/ComponentTypes/SkillType.ts, src/lib/components/Channels/Channels.tsx, src/lib/components/Contact/AboutMe.tsx, src/lib/components/Contact/Contact.tsx, src/lib/components/Contact/ContactForm.tsx, src/lib/components/Gallery/Gallery.tsx, src/lib/components/Image/Image.tsx, src/lib/components/Intro/Intro.tsx, src/lib/components/Intro/IntroForm.tsx, src/lib/components/Intro/IntroTitle.tsx, src/lib/components/Item/Item.tsx, src/lib/components/Skill/Skill.tsx
#164 
1. titleColor
2. shortIntroColor
3. descriptionCOlor
4. descriptionBackgroundColor
1. titleColor
2. subTitleColor
3. buttonTextColor
4. buttonColor
6. buttonBorderColor
1. titleColor
2. descriptionColor
1. titleColor
2. backgroundColor
3. borderColor
4. borderRadius
1. titleColor
2. descriptionColor
3. hoverdInnerBorderColor
1. subheadSize
2. subheadColor
3. headSize
4. headWeight
5. headColor
=> [Feat] add props of Intro, Contact, Skill, Item, Image

src/App.tsx
style(app.tsx): update UI only for testing #164
=> style(app.tsx): update UI only for testing

README.md
1. ProgressBar README 추가
2. 마크다운 코드 이쁘게 수정
=> docs: add ProgressBar description to README and make code beautiful (#152)

src/App.tsx, src/lib/common/types/ComponentTypes/ExperienceType.ts, src/lib/common/types/ComponentTypes/VisitorCommentType.ts, src/lib/common/types/ComponentTypes/VisitorCounterType.ts, src/lib/components/Experience/Experience.tsx, src/lib/components/Experience/History/Basic.tsx, src/lib/components/Experience/History/Box.tsx, src/lib/components/Experience/History/Vertical.tsx, src/lib/components/VisitorComment/CommentInput.tsx, src/lib/components/VisitorComment/CommentList/Basic.tsx, src/lib/components/VisitorComment/CommentList/Box.tsx, src/lib/components/VisitorComment/CommentList/Vertical.tsx, src/lib/components/VisitorComment/VisitorComment.tsx, src/lib/components/VisitorCounter/BigSize.tsx, src/lib/components/VisitorCounter/Default.tsx, src/lib/components/VisitorCounter/Simple.tsx
#164 
Exprience
- headerTitleColor
- dateColor
- descriptionColor
- historyTitleColor
VisitorComment
- listBackgroundColor
- commentColor
- inputFontColor
- inputPlacehoderColor
- listNicknameColor
- listDateColor
VisitorCounter 
- totalBoldColor
- titleColor
- todayTitleColor
- totalTitleColor
=> [Feat] add props in Exprience, VisitorComment, VisitorCounter component (#164)

package-lock.json, package.json, src/App.tsx, src/lib/common/types/ComponentTypes/TechStack/ProgressBarType.ts, src/lib/common/types/ComponentTypes/TechStack/TechStackListType.ts, src/lib/common/types/ComponentTypes/TechStack/TechStackNameType.ts, src/lib/common/types/ComponentTypes/TechStack/TechStackType.ts, src/lib/components/ProgressBar/ProgressBar.tsx, src/lib/components/TechStack/TechStacks/TechStackList.tsx, src/lib/components/TechStack/TechStacks/TechStackName.tsx, src/lib/components/VisitorComment/VisitorComment.tsx
#164 
* none : ```techStackList``` 프롭스의 내부 프로퍼티들에 추가될 프롭스들이 추가되었다.
1. rateText: 기존에 ```rate``` 였던 것을 ```rateText``` 로 변경
2. rateTextColor
3. backgroundColor
1. nameTextColor
1. TechStackList
2. Progressbar
3. nameOption
=> [Feat] add props in TechStackList and ProgressBar, etc.

README.md
Intro, TechStackList, Contact, Skill, Item, Image, Gallery 컴포넌트에서 추가된 props들 관련 README 수정
=> docs: modify README.md about new props (#164)

README.md, src/lib/common/types/ComponentTypes/TechStack/TechStackListType.ts, src/lib/components/TechStack/TechStacks/TechStackList.tsx
=> docs: update documents regarding upgaraded functions

src/App.tsx, src/lib/components/VisitorComment/VisitorComment.tsx, src/lib/components/VisitorCounter/Default.tsx
- 방명록 프로그레스바에 레이트 감추기
- 방문자 계수기 디폴트 테망 하단 패딩 체크
=> feat: change VisitorComment, VisitorCounter components to improve  #164

README.md, src/App.tsx, src/lib/common/types/ComponentTypes/ExperienceType.ts, src/lib/common/types/ComponentTypes/VisitorCommentType.ts, src/lib/components/Experience/Experience.tsx, src/lib/components/VisitorComment/VisitorComment.tsx, src/lib/components/VisitorCounter/Default.tsx
#184 
VisitorComment component
- commentColor -> listCommentColor
=> docs: update typedocs, README.md to changes in v2.0.0  #184

src/App.tsx, src/lib/common/utils/index.ts, src/lib/common/utils/uuidv4.ts, src/lib/components/Carousel/Carousel.tsx, src/lib/components/Channels/Channels.tsx, src/lib/components/Contact/AboutMe.tsx, src/lib/components/Experience/Experience.tsx, src/lib/components/Header/SideContainer/SideBarItems.tsx, src/lib/components/Item/Item.tsx, src/lib/components/TechStack/TechStackInput.tsx, src/lib/components/TechStack/TechStacks/TechStackList.tsx, src/lib/components/VisitorComment/VisitorComment.tsx
=> fix: fix eslint warning (#187)

README.md
=> [Docs] Update README.md of v2.1.1

README.md, src/App.tsx, src/lib/components/VisitorComment/VisitorComment.tsx
> Fix wrong typedoc and readme
=> Fix wrong typedoc and readme

src/lib/components/Item/Item.tsx
> <Item /> 컴포넌트에서 줄바꿈 가능하도록 수정
- Item 
1. Component name
=> fix: enable to line break in Item component (#207)

README.md
=> Fix enable to line break in Item component

src/lib/components/Item/Item.tsx
> Item 컴포넌트에서 textRising 동작 안되던거 수정
#216 
- Item
- no modified props
Attach modified UI picture (not required)
=> [Fix] make textRising works (#216)
